### ISSUE TITLE
Improve README documentation

### ISSUE THREAD

**Issue by Malax** [heroku/heroku-gradle-plugin#27]
See [heroku-maven-plugin](https://github.com/heroku/heroku-maven-plugin) as an example of better documentation for a build tool plugin. Most of the information there also applies to the Gradle plugin and can be ported over.

**Comment by asarkar** [comment]
I don't think people building with Gradle care much about the Maven plugin. This plugin should be able to stand on its own without constantly needing to lean on its elder brother. Thanks for creating a new issue.

**Comment by andrey-agritask** [comment]
Setting

> includeRootDir = project.buildDir

Produces error:

> Could not set unknown property 'includeRootDir' for extension 'heroku' of type com.heroku.sdk.HerokuExtension.

Looks like the README is outdated

**Comment by Malax** [comment]
Closing due to plugin being sunset.
