### ISSUE TITLE
deployHeroku task should depend on stage task

### ISSUE THREAD

**Issue by asarkar** [heroku/heroku-gradle-plugin#28]
The CLI expects a task named [stage](https://devcenter.heroku.com/articles/deploying-gradle-apps-on-heroku#verify-that-your-build-file-is-set-up-correctly), and most people would have set up one (or inherited if using Spring). It'd be helpful to have the plugin depend on task `stage`, if it's present. That'll also eliminate the need for declaring a dependency on whatever task that creates the fat jar (`stage` depends on it already).

**Comment by Malax** [comment]
Closing due to plugin being sunset.
