### ISSUE TITLE
Bump version of com.heroku.sdk:heroku-deploy dependency to 3.0.4

### ISSUE THREAD

**Issue by nikvoloshin** [heroku/heroku-gradle-plugin#30]
Version 3.0.3 of `heroku-deploy` has a [bug](https://github.com/heroku/heroku-maven-plugin/issues/76) that causes failure of `deployHeroku` task.

**Comment by szczebel** [comment]
up. 
are there plans to bump up to 3.0..4 any soon?

@nikvoloshin , have you found any workaround?

**Comment by Malax** [comment]
Closing due to plugin being sunset.
